// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountUp(arg1) {
  return window['go']['main']['App']['CountUp'](arg1);
}
