// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Next() {
  return window['go']['main']['App']['Next']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function StoreCell(arg1, arg2, arg3) {
  return window['go']['main']['App']['StoreCell'](arg1, arg2, arg3);
}
