// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Next():Promise<string>;

export function Start():Promise<string>;

export function StoreCell(arg1:number,arg2:number,arg3:boolean):Promise<string>;
